logging:
  level:
    ROOT: info
server:
  port: ${API_PORT:8081}
  error:
    include-message: always
  servlet:
    context-path: "${CONTEXT_PATH:/}"
spring:
  profiles:
    active: ${ACTIVE_PROFILES:development}
  datasource:
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_CATALOG:demo_social_media}"
    username: "${DB_USERNAME:postgres}"
    password: "${DB_PASSWORD:postgres}"
    hikari:
      minimum-idle: 1
      maximum-pool-size: 50
      idle-timeout: 60000
      pool-name: "demo-social-media-api-db-connection-pool"
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: "public"
        generate_statistics: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 30
        format_sql: true
        show_sql: false
  sql:
    init:
      mode: never
  flyway:
    enabled: true
    schemas: "public"
    locations: "classpath:database"
    validate-migration-naming: true
    clean-disabled: false
    clean-on-validation-error: true

security:
  jwt:
    secret: ${AUTH_JWT_SECRET:social-media-demo-secret-key}
    expiresAfterMs: 172800000
    cookieName: socialMediaDemo
